"""Data models for CoCo reference values."""

import json
from dataclasses import dataclass


RVPS_EXPIRATION = "2099-12-31T00:00:00Z"
RVPS_NAMESPACE = "trustee-operator-system"


@dataclass
class ReferenceValue:
    """A single reference value for Trustee RVPS."""

    name: str
    value: str
    category: str  # executables, hardware, configuration
    description: str
    algorithm: str  # sha256, sha384
    source: str


def format_trustee(values: list[ReferenceValue], platform: str, tee: str) -> str:
    """Format values as a Trustee RVPS ConfigMap YAML."""
    rvps_entries = [
        {"name": v.name, "expiration": RVPS_EXPIRATION, "value": [v.value]}
        for v in values
    ]
    reference_values = json.dumps(rvps_entries, indent=2)

    return (
        f"# Generated by veritas (platform: {platform}, tee: {tee})\n"
        f"apiVersion: v1\n"
        f"kind: ConfigMap\n"
        f"metadata:\n"
        f"  name: rvps-reference-values\n"
        f"  namespace: {RVPS_NAMESPACE}\n"
        f"data:\n"
        f"  reference-values: |\n"
    ) + "\n".join(f"    {line}" for line in reference_values.splitlines()) + "\n"
